# -*- coding: utf-8 -*-
"""Python for Skin Cancer

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jfmgO8ESheNEvcOC9Kr0Y9vh5peavoxI
"""

import tensorflow as tf
import cv2
import numpy as np
import pickle

# from google.colab import drive
# drive.mount('/content/drive')

# os.environ['KAGGLE_CONFIG_DIR'] = "/content/drive/My Drive/Kaggle"
# %cd /content/drive/My Drive/Kaggle

#  lesion_type_dict = {
#     4 : 'Melanocytic nevi',
#     5 : 'Melanoma',
#     2 : 'Benign keratosis-like lesions ',
#     1 : 'Basal cell carcinoma',
#     0 : 'Actinic keratoses',
#     6 : 'Vascular lesions',
#     3 : 'Dermatofibroma'
#   }

base_model =tf.keras.applications.InceptionV3(
                include_top=False,
                weights=None,
                input_tensor=None,
                input_shape=(224,224,3),
                pooling='avg',
                classes=1000,
                classifier_activation="softmax",
               )

    

x=base_model.output
x = tf.keras.layers.Dense(7, activation='softmax')(x)
model_test = tf.keras.models.Model(inputs = base_model.input, outputs = x)

infile = open("weights_only",'rb')
weights_update = pickle.load(infile)
infile.close()

model_test.set_weights(weights=weights_update)

img = cv2.imread('/content/drive/MyDrive/Kaggle/data/HAM10000_images_part_2/ISIC_0029311.jpg')/255 
img_modify_size = cv2.resize(img,(224,224))
img_modify_shape = img_modify_size.reshape(1,224,224,3)
result = model_test(img_modify_shape)
a ,b ,c ,d , e ,f , h  = result[0][0].numpy(),result[0][1].numpy(),result[0][2].numpy(),result[0][3].numpy(),result[0][4].numpy(),result[0][5].numpy(),result[0][6].numpy()
print("1---->" , a*100,"%")
print("2---->" , b*100,"%")
print("3---->" , c*100,"%")
print("4---->" , d*100,"%")
print("5---->" , e*100,"%")
print("6---->" , f*100,"%")
print("7---->" , h*100,"%")